# Generated by Django 2.2.14 on 2020-12-21 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201221_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
