# Generated by Django 2.2.14 on 2020-12-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSecure_Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=256, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
            ],
        ),
    ]
