# Generated by Django 2.2.14 on 2020-12-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bsecure_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsecure_checkout',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bsecure', to='core.Order'),
        ),
    ]
