# Generated by Django 2.2.14 on 2020-12-31 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20201230_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSecure_SSO_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
