# Generated by Django 2.2.14 on 2020-12-31 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bsecure_sso_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsecure_sso_info',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bsecure_sso_info',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sso_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
