# Generated by Django 2.2.14 on 2020-12-31 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201231_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsecure_sso_info',
            name='state_uuid',
            field=models.CharField(default=datetime.datetime(2020, 12, 31, 7, 18, 53, 956006, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
